# uv configuration file
# Extra index URLs for additional package sources
extra-index-url = ["https://pypi.apryse.com"]

# Use the fastest available index
index-strategy = "first-index"

# Cache configuration
cache-dir = ".uv-cache"
